# Generated by Django 6.0 on 2026-01-06 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'IT Support'), ('FIN', 'Finance'), ('OPS', 'Operations'), ('SAL', 'Sales')], default='OPS', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('laptop_model', models.CharField(blank=True, help_text='e.g. Dell Latitude 5420', max_length=100, null=True)),
                ('laptop_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
