# Generated by Django 6.0 on 2026-01-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
