# Generated by Django 6.0 on 2026-01-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_department_incident_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_name',
            field=models.CharField(blank=True, help_text='Type the full name here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, help_text='e.g. HR, Sales, Marketing', max_length=100, null=True),
        ),
    ]
