# Generated by Django 6.0 on 2026-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incident_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
