# Generated by Django 6.0 on 2026-01-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_incident_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='laptop_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='laptop_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
