# Generated by Django 6.0 on 2026-01-23 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_incident_laptop_model_incident_laptop_serial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='it_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='it_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='it_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='it_status_message',
            field=models.TextField(blank=True, help_text='IT status message (e.g., waiting for parts, cannot finish, etc.)', null=True),
        ),
    ]
