# Generated by Django 6.0 on 2026-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_commentread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attached file for incident report', null=True, upload_to='incident_attachments/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of the attached file for VirusTotal scanning', max_length=64, null=True),
        ),
    ]
