# Generated by Django 6.0 on 2026-01-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_alter_comment_options_incident_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network'), ('Account', 'Account'), ('Other', 'Other')], help_text='AI-predicted category for the incident', max_length=50, null=True),
        ),
    ]
