# Generated by Django 6.0 on 2026-01-30 14:00

from django.db import migrations
from django.contrib.auth.management import create_permissions


def create_view_all_global_tickets_permission(apps, schema_editor):
    """Create the view_all_global_tickets permission"""
    # Ensure permissions are created for all apps
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def remove_view_all_global_tickets_permission(apps, schema_editor):
    """Remove the view_all_global_tickets permission"""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        incident_content_type = ContentType.objects.get(
            app_label='incidents',
            model='incident'
        )
        Permission.objects.filter(
            codename='view_all_global_tickets',
            content_type=incident_content_type,
        ).delete()
    except (ContentType.DoesNotExist, Permission.DoesNotExist):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_incident_category'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(
            create_view_all_global_tickets_permission,
            reverse_code=remove_view_all_global_tickets_permission
        ),
    ]
